const quizData = [
  { question: "What is 1 in Malagasy?", answer: "iray" },
  { question: "What is 2 in Malagasy?", answer: "roa" },
  { question: "What is 3 in Malagasy?", answer: "telo" },
  { question: "What is 4 in Malagasy?", answer: "efatra" },
  { question: "What is 5 in Malagasy?", answer: "dimy" },
  { question: "What is 6 in Malagasy?", answer: "enina" },
  { question: "What is 7 in Malagasy?", answer: "fito" },
  { question: "What is 8 in Malagasy?", answer: "valo" },
  { question: "What is 9 in Malagasy?", answer: "sivy" },
  { question: "What is 10 in Malagasy?", answer: "folo" },
  { question: "What is 11 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 12 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 13 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 14 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 15 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 16 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 17 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 18 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 19 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 20 in Malagasy?", answer: "roapolo" },
  { question: "What is 21 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 22 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 23 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 24 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 25 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 26 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 27 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 28 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 29 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 30 in Malagasy?", answer: "telopolo" },
  { question: "What is 31 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 32 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 33 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 34 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 35 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 36 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 37 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 38 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 39 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 40 in Malagasy?", answer: "efapolo" },
  { question: "What is 41 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 42 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 43 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 44 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 45 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 46 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 47 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 48 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 49 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 50 in Malagasy?", answer: "dimampolo" },
  { question: "What is 51 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 52 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 53 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 54 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 55 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 56 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 57 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 58 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 59 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 60 in Malagasy?", answer: "enimpolo" },
  { question: "What is 61 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 62 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 63 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 64 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 65 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 66 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 67 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 68 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 69 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 70 in Malagasy?", answer: "fitopolo" },
  { question: "What is 71 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 72 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 73 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 74 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 75 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 76 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 77 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 78 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 79 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 80 in Malagasy?", answer: "valopolo" },
  { question: "What is 81 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 82 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 83 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 84 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 85 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 86 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 87 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 88 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 89 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 90 in Malagasy?", answer: "sivifolo" },
  { question: "What is 91 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 92 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 93 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 94 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 95 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 96 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 97 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 98 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 99 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 100 in Malagasy?", answer: "zato" },
  { question: "What is 101 in Malagasy?", answer: "iray amby " },
  { question: "What is 102 in Malagasy?", answer: "roa amby " },
  { question: "What is 103 in Malagasy?", answer: "telo amby " },
  { question: "What is 104 in Malagasy?", answer: "efatra amby " },
  { question: "What is 105 in Malagasy?", answer: "dimy amby " },
  { question: "What is 106 in Malagasy?", answer: "enina amby " },
  { question: "What is 107 in Malagasy?", answer: "fito amby " },
  { question: "What is 108 in Malagasy?", answer: "valo amby " },
  { question: "What is 109 in Malagasy?", answer: "sivy amby " },
  { question: "What is 110 in Malagasy?", answer: "folo" },
  { question: "What is 111 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 112 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 113 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 114 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 115 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 116 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 117 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 118 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 119 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 120 in Malagasy?", answer: "roapolo" },
  { question: "What is 121 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 122 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 123 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 124 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 125 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 126 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 127 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 128 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 129 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 130 in Malagasy?", answer: "telopolo" },
  { question: "What is 131 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 132 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 133 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 134 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 135 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 136 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 137 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 138 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 139 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 140 in Malagasy?", answer: "efapolo" },
  { question: "What is 141 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 142 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 143 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 144 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 145 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 146 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 147 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 148 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 149 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 150 in Malagasy?", answer: "dimampolo" },
  { question: "What is 151 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 152 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 153 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 154 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 155 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 156 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 157 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 158 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 159 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 160 in Malagasy?", answer: "enimpolo" },
  { question: "What is 161 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 162 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 163 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 164 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 165 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 166 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 167 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 168 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 169 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 170 in Malagasy?", answer: "fitopolo" },
  { question: "What is 171 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 172 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 173 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 174 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 175 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 176 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 177 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 178 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 179 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 180 in Malagasy?", answer: "valopolo" },
  { question: "What is 181 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 182 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 183 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 184 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 185 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 186 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 187 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 188 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 189 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 190 in Malagasy?", answer: "sivifolo" },
  { question: "What is 191 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 192 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 193 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 194 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 195 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 196 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 197 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 198 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 199 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 200 in Malagasy?", answer: "roanjato" },
  { question: "What is 201 in Malagasy?", answer: "iray amby " },
  { question: "What is 202 in Malagasy?", answer: "roa amby " },
  { question: "What is 203 in Malagasy?", answer: "telo amby " },
  { question: "What is 204 in Malagasy?", answer: "efatra amby " },
  { question: "What is 205 in Malagasy?", answer: "dimy amby " },
  { question: "What is 206 in Malagasy?", answer: "enina amby " },
  { question: "What is 207 in Malagasy?", answer: "fito amby " },
  { question: "What is 208 in Malagasy?", answer: "valo amby " },
  { question: "What is 209 in Malagasy?", answer: "sivy amby " },
  { question: "What is 210 in Malagasy?", answer: "folo" },
  { question: "What is 211 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 212 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 213 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 214 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 215 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 216 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 217 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 218 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 219 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 220 in Malagasy?", answer: "roapolo" },
  { question: "What is 221 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 222 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 223 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 224 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 225 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 226 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 227 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 228 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 229 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 230 in Malagasy?", answer: "telopolo" },
  { question: "What is 231 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 232 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 233 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 234 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 235 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 236 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 237 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 238 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 239 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 240 in Malagasy?", answer: "efapolo" },
  { question: "What is 241 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 242 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 243 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 244 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 245 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 246 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 247 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 248 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 249 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 250 in Malagasy?", answer: "dimampolo" },
  { question: "What is 251 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 252 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 253 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 254 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 255 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 256 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 257 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 258 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 259 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 260 in Malagasy?", answer: "enimpolo" },
  { question: "What is 261 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 262 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 263 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 264 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 265 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 266 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 267 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 268 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 269 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 270 in Malagasy?", answer: "fitopolo" },
  { question: "What is 271 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 272 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 273 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 274 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 275 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 276 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 277 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 278 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 279 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 280 in Malagasy?", answer: "valopolo" },
  { question: "What is 281 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 282 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 283 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 284 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 285 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 286 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 287 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 288 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 289 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 290 in Malagasy?", answer: "sivifolo" },
  { question: "What is 291 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 292 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 293 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 294 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 295 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 296 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 297 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 298 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 299 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 300 in Malagasy?", answer: "telojato" },
  { question: "What is 301 in Malagasy?", answer: "iray amby " },
  { question: "What is 302 in Malagasy?", answer: "roa amby " },
  { question: "What is 303 in Malagasy?", answer: "telo amby " },
  { question: "What is 304 in Malagasy?", answer: "efatra amby " },
  { question: "What is 305 in Malagasy?", answer: "dimy amby " },
  { question: "What is 306 in Malagasy?", answer: "enina amby " },
  { question: "What is 307 in Malagasy?", answer: "fito amby " },
  { question: "What is 308 in Malagasy?", answer: "valo amby " },
  { question: "What is 309 in Malagasy?", answer: "sivy amby " },
  { question: "What is 310 in Malagasy?", answer: "folo" },
  { question: "What is 311 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 312 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 313 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 314 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 315 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 316 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 317 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 318 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 319 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 320 in Malagasy?", answer: "roapolo" },
  { question: "What is 321 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 322 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 323 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 324 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 325 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 326 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 327 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 328 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 329 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 330 in Malagasy?", answer: "telopolo" },
  { question: "What is 331 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 332 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 333 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 334 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 335 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 336 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 337 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 338 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 339 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 340 in Malagasy?", answer: "efapolo" },
  { question: "What is 341 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 342 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 343 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 344 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 345 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 346 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 347 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 348 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 349 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 350 in Malagasy?", answer: "dimampolo" },
  { question: "What is 351 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 352 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 353 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 354 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 355 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 356 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 357 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 358 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 359 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 360 in Malagasy?", answer: "enimpolo" },
  { question: "What is 361 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 362 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 363 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 364 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 365 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 366 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 367 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 368 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 369 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 370 in Malagasy?", answer: "fitopolo" },
  { question: "What is 371 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 372 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 373 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 374 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 375 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 376 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 377 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 378 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 379 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 380 in Malagasy?", answer: "valopolo" },
  { question: "What is 381 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 382 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 383 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 384 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 385 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 386 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 387 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 388 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 389 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 390 in Malagasy?", answer: "sivifolo" },
  { question: "What is 391 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 392 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 393 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 394 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 395 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 396 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 397 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 398 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 399 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 400 in Malagasy?", answer: "efajato" },
  { question: "What is 401 in Malagasy?", answer: "iray amby " },
  { question: "What is 402 in Malagasy?", answer: "roa amby " },
  { question: "What is 403 in Malagasy?", answer: "telo amby " },
  { question: "What is 404 in Malagasy?", answer: "efatra amby " },
  { question: "What is 405 in Malagasy?", answer: "dimy amby " },
  { question: "What is 406 in Malagasy?", answer: "enina amby " },
  { question: "What is 407 in Malagasy?", answer: "fito amby " },
  { question: "What is 408 in Malagasy?", answer: "valo amby " },
  { question: "What is 409 in Malagasy?", answer: "sivy amby " },
  { question: "What is 410 in Malagasy?", answer: "folo" },
  { question: "What is 411 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 412 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 413 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 414 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 415 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 416 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 417 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 418 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 419 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 420 in Malagasy?", answer: "roapolo" },
  { question: "What is 421 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 422 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 423 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 424 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 425 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 426 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 427 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 428 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 429 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 430 in Malagasy?", answer: "telopolo" },
  { question: "What is 431 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 432 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 433 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 434 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 435 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 436 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 437 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 438 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 439 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 440 in Malagasy?", answer: "efapolo" },
  { question: "What is 441 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 442 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 443 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 444 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 445 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 446 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 447 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 448 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 449 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 450 in Malagasy?", answer: "dimampolo" },
  { question: "What is 451 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 452 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 453 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 454 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 455 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 456 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 457 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 458 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 459 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 460 in Malagasy?", answer: "enimpolo" },
  { question: "What is 461 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 462 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 463 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 464 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 465 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 466 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 467 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 468 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 469 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 470 in Malagasy?", answer: "fitopolo" },
  { question: "What is 471 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 472 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 473 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 474 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 475 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 476 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 477 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 478 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 479 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 480 in Malagasy?", answer: "valopolo" },
  { question: "What is 481 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 482 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 483 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 484 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 485 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 486 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 487 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 488 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 489 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 490 in Malagasy?", answer: "sivifolo" },
  { question: "What is 491 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 492 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 493 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 494 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 495 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 496 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 497 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 498 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 499 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 500 in Malagasy?", answer: "dimanjato" },
  { question: "What is 501 in Malagasy?", answer: "iray amby " },
  { question: "What is 502 in Malagasy?", answer: "roa amby " },
  { question: "What is 503 in Malagasy?", answer: "telo amby " },
  { question: "What is 504 in Malagasy?", answer: "efatra amby " },
  { question: "What is 505 in Malagasy?", answer: "dimy amby " },
  { question: "What is 506 in Malagasy?", answer: "enina amby " },
  { question: "What is 507 in Malagasy?", answer: "fito amby " },
  { question: "What is 508 in Malagasy?", answer: "valo amby " },
  { question: "What is 509 in Malagasy?", answer: "sivy amby " },
  { question: "What is 510 in Malagasy?", answer: "folo" },
  { question: "What is 511 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 512 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 513 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 514 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 515 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 516 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 517 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 518 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 519 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 520 in Malagasy?", answer: "roapolo" },
  { question: "What is 521 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 522 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 523 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 524 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 525 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 526 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 527 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 528 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 529 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 530 in Malagasy?", answer: "telopolo" },
  { question: "What is 531 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 532 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 533 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 534 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 535 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 536 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 537 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 538 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 539 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 540 in Malagasy?", answer: "efapolo" },
  { question: "What is 541 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 542 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 543 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 544 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 545 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 546 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 547 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 548 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 549 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 550 in Malagasy?", answer: "dimampolo" },
  { question: "What is 551 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 552 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 553 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 554 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 555 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 556 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 557 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 558 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 559 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 560 in Malagasy?", answer: "enimpolo" },
  { question: "What is 561 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 562 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 563 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 564 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 565 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 566 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 567 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 568 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 569 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 570 in Malagasy?", answer: "fitopolo" },
  { question: "What is 571 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 572 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 573 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 574 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 575 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 576 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 577 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 578 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 579 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 580 in Malagasy?", answer: "valopolo" },
  { question: "What is 581 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 582 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 583 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 584 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 585 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 586 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 587 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 588 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 589 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 590 in Malagasy?", answer: "sivifolo" },
  { question: "What is 591 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 592 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 593 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 594 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 595 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 596 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 597 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 598 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 599 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 600 in Malagasy?", answer: "enin-jato" },
  { question: "What is 601 in Malagasy?", answer: "iray amby " },
  { question: "What is 602 in Malagasy?", answer: "roa amby " },
  { question: "What is 603 in Malagasy?", answer: "telo amby " },
  { question: "What is 604 in Malagasy?", answer: "efatra amby " },
  { question: "What is 605 in Malagasy?", answer: "dimy amby " },
  { question: "What is 606 in Malagasy?", answer: "enina amby " },
  { question: "What is 607 in Malagasy?", answer: "fito amby " },
  { question: "What is 608 in Malagasy?", answer: "valo amby " },
  { question: "What is 609 in Malagasy?", answer: "sivy amby " },
  { question: "What is 610 in Malagasy?", answer: "folo" },
  { question: "What is 611 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 612 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 613 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 614 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 615 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 616 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 617 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 618 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 619 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 620 in Malagasy?", answer: "roapolo" },
  { question: "What is 621 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 622 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 623 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 624 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 625 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 626 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 627 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 628 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 629 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 630 in Malagasy?", answer: "telopolo" },
  { question: "What is 631 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 632 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 633 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 634 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 635 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 636 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 637 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 638 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 639 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 640 in Malagasy?", answer: "efapolo" },
  { question: "What is 641 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 642 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 643 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 644 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 645 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 646 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 647 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 648 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 649 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 650 in Malagasy?", answer: "dimampolo" },
  { question: "What is 651 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 652 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 653 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 654 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 655 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 656 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 657 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 658 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 659 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 660 in Malagasy?", answer: "enimpolo" },
  { question: "What is 661 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 662 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 663 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 664 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 665 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 666 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 667 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 668 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 669 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 670 in Malagasy?", answer: "fitopolo" },
  { question: "What is 671 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 672 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 673 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 674 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 675 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 676 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 677 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 678 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 679 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 680 in Malagasy?", answer: "valopolo" },
  { question: "What is 681 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 682 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 683 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 684 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 685 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 686 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 687 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 688 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 689 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 690 in Malagasy?", answer: "sivifolo" },
  { question: "What is 691 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 692 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 693 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 694 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 695 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 696 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 697 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 698 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 699 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 700 in Malagasy?", answer: "fitonjato" },
  { question: "What is 701 in Malagasy?", answer: "iray amby " },
  { question: "What is 702 in Malagasy?", answer: "roa amby " },
  { question: "What is 703 in Malagasy?", answer: "telo amby " },
  { question: "What is 704 in Malagasy?", answer: "efatra amby " },
  { question: "What is 705 in Malagasy?", answer: "dimy amby " },
  { question: "What is 706 in Malagasy?", answer: "enina amby " },
  { question: "What is 707 in Malagasy?", answer: "fito amby " },
  { question: "What is 708 in Malagasy?", answer: "valo amby " },
  { question: "What is 709 in Malagasy?", answer: "sivy amby " },
  { question: "What is 710 in Malagasy?", answer: "folo" },
  { question: "What is 711 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 712 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 713 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 714 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 715 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 716 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 717 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 718 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 719 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 720 in Malagasy?", answer: "roapolo" },
  { question: "What is 721 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 722 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 723 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 724 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 725 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 726 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 727 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 728 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 729 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 730 in Malagasy?", answer: "telopolo" },
  { question: "What is 731 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 732 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 733 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 734 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 735 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 736 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 737 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 738 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 739 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 740 in Malagasy?", answer: "efapolo" },
  { question: "What is 741 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 742 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 743 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 744 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 745 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 746 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 747 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 748 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 749 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 750 in Malagasy?", answer: "dimampolo" },
  { question: "What is 751 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 752 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 753 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 754 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 755 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 756 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 757 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 758 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 759 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 760 in Malagasy?", answer: "enimpolo" },
  { question: "What is 761 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 762 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 763 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 764 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 765 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 766 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 767 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 768 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 769 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 770 in Malagasy?", answer: "fitopolo" },
  { question: "What is 771 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 772 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 773 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 774 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 775 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 776 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 777 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 778 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 779 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 780 in Malagasy?", answer: "valopolo" },
  { question: "What is 781 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 782 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 783 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 784 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 785 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 786 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 787 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 788 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 789 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 790 in Malagasy?", answer: "sivifolo" },
  { question: "What is 791 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 792 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 793 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 794 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 795 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 796 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 797 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 798 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 799 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 800 in Malagasy?", answer: "valonjato" },
  { question: "What is 801 in Malagasy?", answer: "iray amby " },
  { question: "What is 802 in Malagasy?", answer: "roa amby " },
  { question: "What is 803 in Malagasy?", answer: "telo amby " },
  { question: "What is 804 in Malagasy?", answer: "efatra amby " },
  { question: "What is 805 in Malagasy?", answer: "dimy amby " },
  { question: "What is 806 in Malagasy?", answer: "enina amby " },
  { question: "What is 807 in Malagasy?", answer: "fito amby " },
  { question: "What is 808 in Malagasy?", answer: "valo amby " },
  { question: "What is 809 in Malagasy?", answer: "sivy amby " },
  { question: "What is 810 in Malagasy?", answer: "folo" },
  { question: "What is 811 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 812 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 813 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 814 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 815 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 816 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 817 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 818 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 819 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 820 in Malagasy?", answer: "roapolo" },
  { question: "What is 821 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 822 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 823 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 824 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 825 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 826 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 827 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 828 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 829 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 830 in Malagasy?", answer: "telopolo" },
  { question: "What is 831 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 832 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 833 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 834 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 835 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 836 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 837 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 838 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 839 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 840 in Malagasy?", answer: "efapolo" },
  { question: "What is 841 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 842 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 843 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 844 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 845 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 846 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 847 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 848 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 849 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 850 in Malagasy?", answer: "dimampolo" },
  { question: "What is 851 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 852 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 853 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 854 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 855 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 856 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 857 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 858 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 859 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 860 in Malagasy?", answer: "enimpolo" },
  { question: "What is 861 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 862 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 863 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 864 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 865 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 866 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 867 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 868 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 869 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 870 in Malagasy?", answer: "fitopolo" },
  { question: "What is 871 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 872 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 873 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 874 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 875 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 876 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 877 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 878 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 879 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 880 in Malagasy?", answer: "valopolo" },
  { question: "What is 881 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 882 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 883 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 884 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 885 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 886 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 887 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 888 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 889 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 890 in Malagasy?", answer: "sivifolo" },
  { question: "What is 891 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 892 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 893 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 894 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 895 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 896 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 897 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 898 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 899 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 900 in Malagasy?", answer: "sivinjato" },
  { question: "What is 901 in Malagasy?", answer: "iray amby " },
  { question: "What is 902 in Malagasy?", answer: "roa amby " },
  { question: "What is 903 in Malagasy?", answer: "telo amby " },
  { question: "What is 904 in Malagasy?", answer: "efatra amby " },
  { question: "What is 905 in Malagasy?", answer: "dimy amby " },
  { question: "What is 906 in Malagasy?", answer: "enina amby " },
  { question: "What is 907 in Malagasy?", answer: "fito amby " },
  { question: "What is 908 in Malagasy?", answer: "valo amby " },
  { question: "What is 909 in Malagasy?", answer: "sivy amby " },
  { question: "What is 910 in Malagasy?", answer: "folo" },
  { question: "What is 911 in Malagasy?", answer: "iraika ambin'ny folo" },
  { question: "What is 912 in Malagasy?", answer: "roa ambin'ny folo" },
  { question: "What is 913 in Malagasy?", answer: "telo ambin'ny folo" },
  { question: "What is 914 in Malagasy?", answer: "efatra ambin'ny folo" },
  { question: "What is 915 in Malagasy?", answer: "dimy ambin'ny folo" },
  { question: "What is 916 in Malagasy?", answer: "enina ambin'ny folo" },
  { question: "What is 917 in Malagasy?", answer: "fito ambin'ny folo" },
  { question: "What is 918 in Malagasy?", answer: "valo ambin'ny folo" },
  { question: "What is 919 in Malagasy?", answer: "sivy ambin'ny folo" },
  { question: "What is 920 in Malagasy?", answer: "roapolo" },
  { question: "What is 921 in Malagasy?", answer: "iray amby roapolo" },
  { question: "What is 922 in Malagasy?", answer: "roa amby roapolo" },
  { question: "What is 923 in Malagasy?", answer: "telo amby roapolo" },
  { question: "What is 924 in Malagasy?", answer: "efatra amby roapolo" },
  { question: "What is 925 in Malagasy?", answer: "dimy amby roapolo" },
  { question: "What is 926 in Malagasy?", answer: "enina amby roapolo" },
  { question: "What is 927 in Malagasy?", answer: "fito amby roapolo" },
  { question: "What is 928 in Malagasy?", answer: "valo amby roapolo" },
  { question: "What is 929 in Malagasy?", answer: "sivy amby roapolo" },
  { question: "What is 930 in Malagasy?", answer: "telopolo" },
  { question: "What is 931 in Malagasy?", answer: "iray amby telopolo" },
  { question: "What is 932 in Malagasy?", answer: "roa amby telopolo" },
  { question: "What is 933 in Malagasy?", answer: "telo amby telopolo" },
  { question: "What is 934 in Malagasy?", answer: "efatra amby telopolo" },
  { question: "What is 935 in Malagasy?", answer: "dimy amby telopolo" },
  { question: "What is 936 in Malagasy?", answer: "enina amby telopolo" },
  { question: "What is 937 in Malagasy?", answer: "fito amby telopolo" },
  { question: "What is 938 in Malagasy?", answer: "valo amby telopolo" },
  { question: "What is 939 in Malagasy?", answer: "sivy amby telopolo" },
  { question: "What is 940 in Malagasy?", answer: "efapolo" },
  { question: "What is 941 in Malagasy?", answer: "iray amby efapolo" },
  { question: "What is 942 in Malagasy?", answer: "roa amby efapolo" },
  { question: "What is 943 in Malagasy?", answer: "telo amby efapolo" },
  { question: "What is 944 in Malagasy?", answer: "efatra amby efapolo" },
  { question: "What is 945 in Malagasy?", answer: "dimy amby efapolo" },
  { question: "What is 946 in Malagasy?", answer: "enina amby efapolo" },
  { question: "What is 947 in Malagasy?", answer: "fito amby efapolo" },
  { question: "What is 948 in Malagasy?", answer: "valo amby efapolo" },
  { question: "What is 949 in Malagasy?", answer: "sivy amby efapolo" },
  { question: "What is 950 in Malagasy?", answer: "dimampolo" },
  { question: "What is 951 in Malagasy?", answer: "iray amby dimampolo" },
  { question: "What is 952 in Malagasy?", answer: "roa amby dimampolo" },
  { question: "What is 953 in Malagasy?", answer: "telo amby dimampolo" },
  { question: "What is 954 in Malagasy?", answer: "efatra amby dimampolo" },
  { question: "What is 955 in Malagasy?", answer: "dimy amby dimampolo" },
  { question: "What is 956 in Malagasy?", answer: "enina amby dimampolo" },
  { question: "What is 957 in Malagasy?", answer: "fito amby dimampolo" },
  { question: "What is 958 in Malagasy?", answer: "valo amby dimampolo" },
  { question: "What is 959 in Malagasy?", answer: "sivy amby dimampolo" },
  { question: "What is 960 in Malagasy?", answer: "enimpolo" },
  { question: "What is 961 in Malagasy?", answer: "iray amby enimpolo" },
  { question: "What is 962 in Malagasy?", answer: "roa amby enimpolo" },
  { question: "What is 963 in Malagasy?", answer: "telo amby enimpolo" },
  { question: "What is 964 in Malagasy?", answer: "efatra amby enimpolo" },
  { question: "What is 965 in Malagasy?", answer: "dimy amby enimpolo" },
  { question: "What is 966 in Malagasy?", answer: "enina amby enimpolo" },
  { question: "What is 967 in Malagasy?", answer: "fito amby enimpolo" },
  { question: "What is 968 in Malagasy?", answer: "valo amby enimpolo" },
  { question: "What is 969 in Malagasy?", answer: "sivy amby enimpolo" },
  { question: "What is 970 in Malagasy?", answer: "fitopolo" },
  { question: "What is 971 in Malagasy?", answer: "iray amby fitopolo" },
  { question: "What is 972 in Malagasy?", answer: "roa amby fitopolo" },
  { question: "What is 973 in Malagasy?", answer: "telo amby fitopolo" },
  { question: "What is 974 in Malagasy?", answer: "efatra amby fitopolo" },
  { question: "What is 975 in Malagasy?", answer: "dimy amby fitopolo" },
  { question: "What is 976 in Malagasy?", answer: "enina amby fitopolo" },
  { question: "What is 977 in Malagasy?", answer: "fito amby fitopolo" },
  { question: "What is 978 in Malagasy?", answer: "valo amby fitopolo" },
  { question: "What is 979 in Malagasy?", answer: "sivy amby fitopolo" },
  { question: "What is 980 in Malagasy?", answer: "valopolo" },
  { question: "What is 981 in Malagasy?", answer: "iray amby valopolo" },
  { question: "What is 982 in Malagasy?", answer: "roa amby valopolo" },
  { question: "What is 983 in Malagasy?", answer: "telo amby valopolo" },
  { question: "What is 984 in Malagasy?", answer: "efatra amby valopolo" },
  { question: "What is 985 in Malagasy?", answer: "dimy amby valopolo" },
  { question: "What is 986 in Malagasy?", answer: "enina amby valopolo" },
  { question: "What is 987 in Malagasy?", answer: "fito amby valopolo" },
  { question: "What is 988 in Malagasy?", answer: "valo amby valopolo" },
  { question: "What is 989 in Malagasy?", answer: "sivy amby valopolo" },
  { question: "What is 990 in Malagasy?", answer: "sivifolo" },
  { question: "What is 991 in Malagasy?", answer: "iray amby sivifolo" },
  { question: "What is 992 in Malagasy?", answer: "roa amby sivifolo" },
  { question: "What is 993 in Malagasy?", answer: "telo amby sivifolo" },
  { question: "What is 994 in Malagasy?", answer: "efatra amby sivifolo" },
  { question: "What is 995 in Malagasy?", answer: "dimy amby sivifolo" },
  { question: "What is 996 in Malagasy?", answer: "enina amby sivifolo" },
  { question: "What is 997 in Malagasy?", answer: "fito amby sivifolo" },
  { question: "What is 998 in Malagasy?", answer: "valo amby sivifolo" },
  { question: "What is 999 in Malagasy?", answer: "sivy amby sivifolo" },
  { question: "What is 1000 in Malagasy?", answer: "arivo" },
];

function startQuiz(data) {
  let current = null;
  const questionEl = document.getElementById('quiz-question');
  const resultEl = document.getElementById('quiz-result');
  const inputEl = document.getElementById('quiz-answer');

  window.newQuiz = function() {
    current = data[Math.floor(Math.random() * data.length)];
    questionEl.textContent = current.question;
    resultEl.textContent = "";
    inputEl.value = "";
  }

  window.checkAnswer = function() {
    const userAns = inputEl.value.trim().toLowerCase();
    const correctAns = current.answer.toLowerCase();
    resultEl.textContent = userAns === correctAns
      ? "Correct!"
      : `Wrong! The correct answer is: "${current.answer}"`;
  }

  newQuiz();
}

document.addEventListener("DOMContentLoaded", function () {
    function loadHeaderFooter() {
        const headerContainer = document.getElementById("header");
        const footerContainer = document.getElementById("footer");

        // ✅ Fetch from the same `/bako/introduction/` folder
        const headerPath = "header.html";  
        const footerPath = "footer.html";  

        console.log(`Fetching Header from: ${headerPath}`);
        console.log(`Fetching Footer from: ${footerPath}`);

        if (headerContainer) {
            fetch(headerPath)
                .then(response => {
                    if (!response.ok) throw new Error(`Failed to load ${headerPath}`);
                    return response.text();
                })
                .then(data => {
                    console.log("Header loaded successfully!");
                    headerContainer.innerHTML = data;
                })
                .catch(error => console.error("Error loading header:", error));
        }

     

        if (footerContainer) {
            fetch(footerPath)
                .then(response => {
                    if (!response.ok) throw new Error(`Failed to load ${footerPath}`);
                    return response.text();
                })
                .then(data => {
                    console.log("Footer loaded successfully!");
                    footerContainer.innerHTML = data;
                })
                .catch(error => console.error("Error loading footer:", error));
        }
    }

    loadHeaderFooter();
});

// Dynamically inject Google Analytics tag globally
(function () {
  const ga = document.createElement("script");
  ga.src = "https://www.googletagmanager.com/gtag/js?id=G-DG828TL4V1";
  ga.async = true;
  document.head.appendChild(ga);

  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());
  gtag('config', 'G-DG828TL4V1');
})();
